# Generated by Django 5.0.10 on 2025-01-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tramite', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('pais_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo_viaje', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_visa', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_pasaporte', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=50, null=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion_contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
